vim.opt.completeopt={ "menu", "menuone", "noselect" }
vim.opt.showmode = false
vim.opt.hlsearch = false
vim.opt.exrc = true
vim.opt.number = true
vim.opt.hidden = true
vim.opt.relativenumber = true
vim.opt.errorbells = false
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.fixendofline = false
-- vim.opt.undodir=~/.cache/nvim/undodir
vim.opt.undofile = true
vim.opt.scrolloff=8
vim.opt.tabstop=4
vim.opt.softtabstop=4
vim.opt.shiftwidth=4
vim.opt.shell="/bin/zsh"
vim.opt.clipboard="unnamedplus"
vim.opt.signcolumn = "yes"
vim.g.mapleader = " "
