set completeopt=menu,menuone,noselect
set noshowmode
set nohlsearch
set exrc
set number
set hidden
set relativenumber
set noerrorbells
set nowrap
set noswapfile
set nobackup
set expandtab
set smartindent
set undodir=~/.cache/nvim/undodir
set undofile
set scrolloff=8
set tabstop=4 softtabstop=4
set shiftwidth=4
set shell=/bin/zsh
set clipboard=unnamedplus
set signcolumn=yes
