#! /bin/sh

# start programs
sxhkd &
compton &
nm-applet &
blueman-applet &
flameshot &
/usr/bin/dunst &
keybase service &

# load colors 
wal --theme $HOME/.config/colors.json

# fix java app issues with tiling wm
wmname LG3D

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xrandr

if [ $(hostname) = rustyDesktop ]
then
    xrandr --output DP-4 --auto --primary
    xrandr --output DP-3 --auto --right-of DP-4 --rotate left
    xrandr --output HDMI-4 --auto --right-of DP-3


    bspc monitor DP-4 -d I II III IV V VI 
    bspc monitor DP-3 -d VII VIII IX
    bspc monitor HDMI-4 -d X

elif [ $(hostname) = rustyLaptop ]
then
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

# Reload wallpapers
nitrogen --restore

$HOME/.scripts/launch_polybar.sh
