#! /bin/sh

feh --bg-scale $HOME/Images/wallpaper.jpg
sxhkd &
compton &
nm-applet &
blueman-applet &
$HOME/.scripts/launch_polybar.sh &

# fix java app issues with tiling wm
wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

