#! /bin/sh

xrdb ~/.config/X11/Xresources

# start programs
sxhkd &
picom &
flameshot &
/usr/bin/dunst &
light-locker &

# fix java app issues with tiling wm
wmname LG3D

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus    true

bspc rule -r '*'
bspc rule -a \* state=tiled layer=normal

if [ $(hostname) = rustyDesktop ]
then
    autorandr --load desktop
    bspc monitor DisplayPort-1 -d 1 2 3 4 5
    bspc monitor DisplayPort-2 -d 6 7 8
    bspc monitor HDMI-A-0 -d 9 0

elif [ $(hostname) = rustyLaptop ]
then
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
    # Only start nm-applet on laptop
    nm-applet &
fi

# Reload wallpapers
nitrogen --restore

$HOME/.scripts/launch_polybar.sh

