location:
    source_directories:
        - /home/wouter/Documents/notes

    repositories:
        - ssh://adns088m@adns088m.repo.borgbase.com/./repo

    # Any paths matching these patterns are included/excluded from
    # backups. Globs are expanded. (Tildes are not.) See the
    # output of "borg help patterns" for more details. Quote any
    # value if it contains leading punctuation, so it parses
    # correctly. Note that only one of "patterns" and
    # "source_directories" may be used.
    # patterns:
        # - R /
        # - '- /home/*/.cache'
        # - + /home/susan
        # - '- /home/*'

    # Read include/exclude patterns from one or more separate
    # named files, one pattern per line. Note that Borg considers
    # this option experimental. See the output of "borg help
    # patterns" for more details.
    # patterns_from:
        # - /etc/borgmatic/patterns

    # Any paths matching these patterns are excluded from backups.
    # Globs and tildes are expanded. Note that a glob pattern must
    # either start with a glob or be an absolute path. Do not
    # backslash spaces in path names. See the output of "borg help
    # patterns" for more details.
    # exclude_patterns:
        # - '*.pyc'
        # - /home/*/.cache
        # - '*/.vim*.tmp'
        # - /etc/ssl
        # - /home/user/path with spaces

    # Read exclude patterns from one or more separate named files,
    # one pattern per line. See the output of "borg help patterns"
    # for more details.
    # exclude_from:
        # - /etc/borgmatic/excludes

    # Exclude directories that contain a CACHEDIR.TAG file. See
    # http://www.brynosaurus.com/cachedir/spec.html for details.
    # Defaults to false.
    # exclude_caches: true

    # Exclude directories that contain a file with the given
    # filenames. Defaults to not set.
    # exclude_if_present:
        # - .nobackup

    # If true, the exclude_if_present filename is included in
    # backups. Defaults to false, meaning that the
    # exclude_if_present filename is omitted from backups.
    # keep_exclude_tags: true

# storage:
    # encryption_passcommand: secret-tool lookup borg-repository repo-name
    # encryption_passphrase: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
    # archive_name_format: '{hostname}-documents-{now}'
retention:
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 12

